import type { Team } from "../../types";

export const teams: Team[] = [
  {
    id: 1,
    name: "Team A",
    captainName: "John Doe",
    captainEmail: "john@example.com",
    members: ["Alice", "Bob", "Charlie"],
  },
  {
    id: 2,
    name: "Team B",
    captainName: "Jane Smith",
    captainEmail: "jane@example.com",
    members: ["David", "Eve", "Frank"],
  },
  {
    id: 3,
    name: "Team C",
    captainName: "Mike Johnson",
    captainEmail: "mike@example.com",
    members: ["Grace", "Heidi", "Ivan"],
  },
  {
    id: 4,
    name: "Team D",
    captainName: "Emily Davis",
    captainEmail: "emily@example.com",
    members: ["Jack", "Liam", "Olivia"],
  },
  {
    id: 5,
    name: "Team E",
    captainName: "Chris Brown",
    captainEmail: "chris@example.com",
    members: ["Mallory", "Niaj", "Olivia"],
  },
  {
    id: 6,
    name: "Team F",
    captainName: "Alice Wonderland",
    captainEmail: "alice@example.com",
    members: ["Bob", "Charlie", "David"],
  },
  {
    id: 7,
    name: "Team G",
    captainName: "Bob Builder",
    captainEmail: "bob@example.com",
    members: ["Alice", "Charlie", "David"],
  },
  {
    id: 8,
    name: "Team H",
    captainName: "Charlie Brown",
    captainEmail: "charlie@example.com",
    members: ["David", "Eve", "Frank"],
  },
  {
    id: 9,
    name: "Team I",
    captainName: "David Tennant",
    captainEmail: "david@example.com",
    members: ["Eve", "Frank", "Grace"],
  },
  {
    id: 10,
    name: "Team J",
    captainName: "Emma Watson",
    captainEmail: "emma@example.com",
    members: ["Alice", "Bob", "Charlie"],
  },
  {
    id: 11,
    name: "Team K",
    captainName: "Fiona Apple",
    captainEmail: "fiona@example.com",
    members: ["Grace", "Heidi", "Ivan"],
  },
  {
    id: 12,
    name: "Team L",
    captainName: "George Martin",
    captainEmail: "george@example.com",
    members: ["Jack", "Liam", "Olivia"],
  },
  {
    id: 13,
    name: "Team M",
    captainName: "Hannah Arendt",
    captainEmail: "hannah@example.com",
    members: ["Jack", "Liam", "Olivia"],
  },
  {
    id: 14,
    name: "Team N",
    captainName: "Ian McKellen",
    captainEmail: "ian@example.com",
    members: ["Jack", "Liam", "Olivia"],
  },
  {
    id: 15,
    name: "Team O",
    captainName: "J.K. Rowling",
    captainEmail: "jk@example.com",
    members: ["Harry", "Hermione", "Ron"],
  },
];
